GET http://localhost:8000/member/member/count
Accept: application/json

###

# 快速生成 ptrp
POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=13800138003

###

POST http://localhost:8000/member/member/send-code
Content-Type: application/x-www-form-urlencoded

mobile=13800138000

###
